[versions]
coroutines = "1.11.0"
androidXCore = "1.19.0"
navigation = "2.9.8"
lifecycle = "2.11.0"
material = "1.14.0"
retrofit-core = "3.0.0"
okHttp-core = "5.4.0"
okHttp-logging = "5.4.0"
moshi = "1.15.2"
ktor = "3.5.2"
kotlinxSerialization = "1.11.0"
koin-android = "4.2.2"
coil-core = "3.5.0"
coil-svg = "3.5.0"
espresso = "3.7.0"
mockito = "5.23.0"
mockito_inline = "5.2.0"
mockito_kotlin = "6.3.0"
junit = "6.1.2"
junit_ktx = "1.3.0"
support_runner = "1.7.0"
truth = "1.4.5"
compose_bom = "2026.06.01"
composeActivity = "1.13.0"
composeLifecycle = "2.11.0"
constraintlayoutCompose = "1.1.2"
androidGradlePlugin = "9.2.1"
kotlin = "2.4.10"

[libraries]
andoidx-core = { group = "androidx.core", name = "core", version.ref = "androidXCore" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidXCore" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
coil = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil-core" }
coil-svg = { group = "io.coil-kt.coil3", name = "coil-svg", version.ref = "coil-svg" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil-core" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil-core" }
okHttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp-core" }
okHttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okHttp-logging" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit-core" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit-core" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin-android"}
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin-android"}
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin-android" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito_inline" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito_kotlin" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "support_runner" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "support_runner" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
espresso-web = { group = "androidx.test.espresso", name = "espresso-web", version.ref = "espresso" }
espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso" }
mockito-android = { group = "org.mockito", name = "mockito-android", version.ref = "mockito" }
test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "support_runner" }
junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junit_ktx" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okHttp-core" }
okhttp3-idling-resource = { group = "com.jakewharton.espresso", name = "okhttp3-idling-resource", version = "1.0.0" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose_bom" }
compose-animation = { group = "androidx.compose.animation", name = "animation" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeLifecycle" }
compose-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "composeLifecycle" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }

[bundles]
compose-ui = [
    "compose-animation",
    "compose-foundation",
    "compose-material3",
    "compose-material-icons-extended",
    "compose-runtime",
    "compose-ui",
    "compose-constraintlayout",
    "compose-activity",
    "compose-lifecycle-viewmodel",
    "compose-lifecycle-runtime",
    "compose-ui-tooling-preview",
]
ui = [
    "andoidx-core", "androidx-core-ktx", "coroutines", "material", "navigation-compose",
]
lifecycle = [
    "lifecycle-viewmodel-ktx", "lifecycle-livedata-ktx", "lifecycle-common-java8",
    "lifecycle-runtime-ktx"
]
remoteImages = ["coil", "coil-svg", "coil-compose", "coil-network-okhttp"]
network = [
    "okHttp", "okHttp-logging", "retrofit", "retrofit-moshi", "moshi-adapters"
]
ktor = [
    "ktor-client-core", "ktor-client-okhttp", "ktor-client-content-negotiation",
    "ktor-client-logging", "ktor-serialization-kotlinx-json", "kotlinx-serialization-json"
]
test = [
    "junit-jupiter-api", "junit-jupiter-params", "mockito-core", "mockito-inline", "mockito-kotlin",
    "truth", "coroutines-test"
]
androidTest = [
    "test-runner", "test-rules", "espresso-core", "espresso-web", "espresso-contrib",
    "espresso-intents", "mockito-android", "test-core-ktx", "junit-ktx",
    "truth", "mockwebserver", "okhttp3-idling-resource"
]
[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.3.10" }
