import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.android.kotlin)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.serialization)
}

val localProperties = Properties().apply {
    val file = rootProject.file("local.properties")
    if (file.exists()) file.inputStream().use { load(it) }
}

android {
    compileSdk = 37

    defaultConfig {
        applicationId = "com.measton.dogapp"
        minSdk = 24
        targetSdk = 37
        versionCode = 1
        versionName = "1.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }


    buildTypes {
        named("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    namespace = "com.measton.dogapp"
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation(libs.bundles.ui)
    implementation(libs.bundles.lifecycle)
    implementation(libs.bundles.remoteImages)
    testImplementation(libs.bundles.test)
    implementation(libs.bundles.ktor)
    testImplementation(kotlin("test"))
    androidTestImplementation(libs.bundles.androidTest)
    implementation(libs.koin.android)
    implementation(libs.koin.androidx.compose)
    testImplementation(libs.koin.test)
    implementation(platform(libs.compose.bom))
    implementation(libs.bundles.compose.ui)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.manifest)
    androidTestImplementation(libs.compose.junit4)
    testImplementation(libs.ktor.client.mock)
}

/**
 * Writes the API key into a generated Kotlin source file instead of BuildConfig, which is
 * generated by AGP for Android only. In Phase 5 this same output feeds commonMain, so the
 * key reaches iOS and Desktop by exactly the same route.
 */
abstract class GenerateApiKey : DefaultTask() {

    @get:Input
    @get:Optional
    abstract val apiKey: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val key = apiKey.orNull?.takeIf { it.isNotBlank() } ?: error(
            "DOG_API_KEY is missing from local.properties. " +
                "Copy local.properties.example and add a key from https://thedogapi.com."
        )
        val escaped = key.replace("\\", "\\\\").replace("\"", "\\\"")
        outputDir.get().file("com/measton/dogapp/ApiKey.kt").asFile.apply {
            parentFile.mkdirs()
            writeText(
                """
                package com.measton.dogapp

                internal const val DOG_API_KEY = "$escaped"
                """.trimIndent() + "\n"
            )
        }
    }
}

val generateApiKey = tasks.register<GenerateApiKey>("generateApiKey") {
    apiKey.set(localProperties.getProperty("DOG_API_KEY"))
    outputDir.set(layout.buildDirectory.dir("generated/apikey"))
}

androidComponents {
    onVariants { variant ->
        variant.sources.kotlin?.addGeneratedSourceDirectory(generateApiKey) { it.outputDir }
    }
}
